import { Fragment, useState } from 'react'

export default function AIReport({ report, loading }) {
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(report)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      /* clipboard unavailable */
    }
  }

  return (
    // Animated gradient border: a gradient-filled wrapper with a 1px inset card.
    <div className="rounded-xl bg-gradient-to-r from-purple-600/60 via-blue-500/60 to-purple-600/60 bg-[length:200%_200%] animate-gradient p-px">
      <div className="rounded-[11px] bg-gradient-to-br from-purple-950/30 via-neutral-900 to-neutral-900 p-6">
        <div className="mb-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h2 className="text-sm font-semibold text-neutral-100">AI Analysis</h2>
            <span className="inline-flex items-center gap-1 rounded-full border border-purple-500/30 bg-purple-500/10 px-2 py-0.5 text-[11px] font-medium text-purple-300">
              <span className="text-purple-400">✦</span>
              Generated by AI
            </span>
          </div>
          {report && !loading && (
            <button
              onClick={copy}
              className="rounded-md border border-neutral-700 px-3 py-1.5 text-xs font-medium text-neutral-400 hover:border-neutral-500 hover:text-neutral-200 transition-colors"
            >
              {copied ? 'Copied' : 'Copy'}
            </button>
          )}
        </div>

        {loading ? (
          <div className="flex items-center gap-3 py-8 text-sm text-neutral-400">
            <span className="h-4 w-4 animate-spin rounded-full border-2 border-purple-500/30 border-t-purple-400" />
            {report ? 'Analyzing…' : 'Running test…'}
          </div>
        ) : report ? (
          <div className="space-y-1">{renderReport(report)}</div>
        ) : (
          <p className="py-8 text-sm text-neutral-600">
            Run a test to generate an AI performance analysis.
          </p>
        )}
      </div>
    </div>
  )
}

// renderReport turns the model's markdown-ish text into styled elements:
// `## ` headings, numbered list items with a badge, and inline **bold**.
function renderReport(text) {
  return text.split('\n').map((line, i) => {
    const trimmed = line.trim()

    if (!trimmed) return <div key={i} className="h-2" />

    if (trimmed.startsWith('## ') || trimmed.startsWith('# ')) {
      const heading = trimmed.replace(/^#+\s+/, '')
      return (
        <div key={i} className="mt-5 first:mt-0">
          <h3 className="text-sm font-semibold uppercase tracking-wide text-purple-300">
            {renderInline(heading)}
          </h3>
          <div className="mt-1.5 h-px w-full bg-gradient-to-r from-purple-500/50 via-blue-500/30 to-transparent" />
        </div>
      )
    }

    const numbered = trimmed.match(/^(\d+)\.\s+(.*)$/)
    if (numbered) {
      return (
        <div key={i} className="mt-2 flex items-start gap-3">
          <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-purple-500 to-blue-500 text-[11px] font-bold text-white">
            {numbered[1]}
          </span>
          <p className="text-sm leading-relaxed text-neutral-300">
            {renderInline(numbered[2])}
          </p>
        </div>
      )
    }

    return (
      <p key={i} className="text-sm leading-relaxed text-neutral-300">
        {renderInline(trimmed)}
      </p>
    )
  })
}

// renderInline renders **bold** spans within a line of text.
function renderInline(text) {
  return text.split(/\*\*/).map((part, i) =>
    i % 2 === 1 ? (
      <strong key={i} className="font-semibold text-neutral-100">
        {part}
      </strong>
    ) : (
      <Fragment key={i}>{part}</Fragment>
    ),
  )
}
